# Generated by Django 4.1.3 on 2022-12-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Resolved',
            field=models.BooleanField(default=False),
        ),
    ]
